name: TrueDeploy-Curl-to-AWS
author: TrueDeploy
description: Github action to send data to the TrueDeploy's infrastructure using Curl
branding:
  icon: 'upload-cloud'
  color: 'blue'

runs:
  using: "composite"
  steps: 
    - name: Echo
      shell: bash
      run: |
        echo This is the TrueDeploy-Curl-to-AWS GitHub Action with API Key Support

    - name: Check out TrueDeploy-Curl-to-AWS repository code
      uses: actions/checkout@v3
      with:
          repository: TrueDeploy-com/TrueDeploy-Curl-to-AWS
          ref: feature/add-apikey-support # remove this line after merge into main
          path: ./TrueDeploy-Curl-to-AWS
