#! /bin/bash
#
# TrueDeploy-Curl-to-AWS GitHub Action
# Copyright (c) TrueDeploy
#
# This product includes software developed by TrueDeploy (https://truedeploy.com/).
#
#

ACTION="$1"
URL="$2"
ENDPOINT="$3"
API_KEY="$4"
CREATE_RECORD="$5"

if [ "$ACTION" == "POST" ]; then
    curl --location --request "$ACTION" --url "${URL}/${ENDPOINT}" -H "APIkey: $API_KEY" -H "Content-Type: application/json" -d "$CREATE_RECORD"
elif [ "$ACTION" == "FILE" ]; then
    curl --location --request "POST" --url "${URL}/${ENDPOINT}" -H "APIkey: $API_KEY" -H "Content-Type: application/json" -d "@$CREATE_RECORD"
fi